#!/usr/bin/env bash

set -uo pipefail
trap 's=$?; echo "$0: Error on line "$LINENO": $BASH_COMMAND"; exit $s' ERR

exec 1> >(tee "bootstrap.out.log")
exec 2> >(tee "bootstrap.err.log" >&2)

mkdir -p $HOME/.config/fontconfig/conf.d
ln -s -f /usr/share/fontconfig/conf.avail/50-user.conf $XDG_CONFIG_HOME/fontconfig/conf.d

mkdir -p $HOME/.local/state/bash

