[font]
size = 16.0

[font.normal]
family = "FantasqueSansM Nerd Font Mono"
style = "Regular"

[font.bold]
family = "FantasqueSansM Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "FantasqueSansM Nerd Font Mono"
style = "Blod Italic"

[font.italic]
family = "FantasqueSansM Nerd Font Mono"
style = "Italic"
