import = ["/home/oliverdding/.config/alacritty/config.d/bell.toml", "/home/oliverdding/.config/alacritty/config.d/colors.toml", "/home/oliverdding/.config/alacritty/config.d/cursor.toml", "/home/oliverdding/.config/alacritty/config.d/font.toml", "/home/oliverdding/.config/alacritty/config.d/keys.toml", "/home/oliverdding/.config/alacritty/config.d/mouse.toml", "/home/oliverdding/.config/alacritty/config.d/window.toml"]
live_config_reload = true

[env]
TERM = "alacritty"

[[hints.enabled]]
command = "xdg-open"
hyperlinks = true
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.binding]
key = "U"
mods = "Control|Shift"

[hints.enabled.mouse]
enabled = true
mods = "None"

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"
