theme = "everforest_dark"

[editor]
line-number = "relative"
cursorline = true
true-color = true # for ssh
bufferline = "multiple"
color-modes = true
default-line-ending = "lf"

[editor.soft-wrap]
enable = true

[editor.statusline]
left = ["mode", "spacer", "file-name", "file-modification-indicator", "spacer", "spinner"]
right = ["diagnostics", "spacer", "version-control", "spacer", "selections", "spacer", "position-percentage", "spacer", "file-type"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.whitespace.render]
space = "all"
tab = "all"
newline = "none"

[editor.indent-guides]
render = true
skip-levels = 1

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
C-j = "jump_view_down"
C-k = "jump_view_up"
C-h = "jump_view_left"
C-l = "jump_view_right"
C-u = ["half_page_up", "align_view_center"]
C-d = ["half_page_down", "align_view_center"]
"@" = [
  "move_prev_word_start",
  "move_next_word_end",
  "search_selection",
  "global_search",
]

[keys.normal.space]
x = ":buffer-close"
l = ":toggle lsp.display-inlay-hints"
