[[language]]
name = "rust"

[[language]]
name = "go"

[language-server.gopls.config]
gofumpt = true
analyses = { "fieldalignment" = true, "nilness" = true, "unusedvariable" = true }
staticcheck = true
vulncheck = "Imports"

[[language]]
name = "typescript"
formatter = { command = "prettier" }
auto-format = true

[[language]]
name = "toml"
formatter = { command = "prettier" }
auto-format = true

[[language]]
name = "yaml"
formatter = { command = "prettier" }
auto-format = true
