[[language]]
name = "rust"
formatter = { command = "rustfmt" }

[[language]]
name = "go"

[[language]]
name = "typescript"
formatter = { command = "prettier" }
auto-format = true

[[language]]
name = "toml"
formatter = { command = "prettier" }
auto-format = true

[[language]]
name = "yaml"
formatter = { command = "prettier" }
auto-format = true
